-- Optional seed (use Supabase SQL editor)
insert into public.places (name, description, significance, travel_tips, category, city, country, address, latitude, longitude, hours, website, tags, rating)
values
('Key Monastery (Kye Gompa)', 'A 1,000-year-old Tibetan Buddhist monastery perched on a hill in Spiti Valley.', 'Spiritual center of Spiti and an architectural marvel.', '{Carry warm clothing year-round,Altitude acclimatization recommended}', 'temple', 'Spiti', 'India', null, 32.3107, 78.0435, '6:00–18:00', 'https://en.wikipedia.org/wiki/Key_Monastery', '{spiritual,heritage,buddhist}', 4.8),
('Solang Valley', 'Open valley near Manali famous for paragliding, skiing, and scenic views.', 'Adventure hotspot close to Manali.', '{Best visited early morning,Check weather for activities}', 'adventure', 'Manali', 'India', null, 32.3187, 77.1554, null, null, '{paragliding,skiing}', 4.6),
('Rohtang Pass', 'Mountain pass on the Pir Panjal range with stunning vistas.', 'Gateway to Lahaul and Spiti valleys.', '{Permit required,Closed in winter due to snow}', 'landmark', 'Manali', 'India', null, 32.3668, 77.2481, null, null, '{scenic,drive}', 4.7),
('Cafe 1947', 'Iconic riverside cafe with live music and Italian cuisine.', 'Popular hangout for travelers in Manali.', '{Expect wait times during peak season}', 'cafe', 'Manali', 'India', 'Old Manali, Manali', 32.2437, 77.1882, null, null, '{cafe,italian}', 4.5),
('Johnson''s Cafe', 'Longstanding restaurant known for trout and cocktails.', 'Local favorite for hearty meals.', '{Try the trout,Evenings can be lively}', 'restaurant', 'Manali', 'India', 'Circuit House Rd, Siyal, Manali', 32.2442, 77.189, null, null, '{restaurant,trout}', 4.4),
('Parvati River Viewpoint', 'Rushing turquoise river flanked by tall pines.', 'Ideal for short hikes and relaxing by the water.', '{Wear sturdy shoes,Beware of slippery rocks}', 'park', 'Kasol', 'India', null, 32.01, 77.317, null, null, '{river,hike}', 4.5),
('HPCA Cricket Stadium', 'Scenic international cricket stadium with mountain backdrop.', 'One of the most picturesque stadiums in the world.', '{Check event schedules for access}', 'landmark', 'Dharamshala', 'India', null, 32.1976, 76.3258, null, null, '{stadium,cricket}', 4.6),
('Manali Bus Stand', 'Transport hub connecting Himachal towns.', 'Useful for planning onward journeys.', '{Keep some cash for tickets,Arrive early in peak season}', 'transport', 'Manali', 'India', null, 32.2425, 77.1896, null, null, '{bus,transport}', 4.0);
